apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rating-read-service
  namespace: bsk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rating-read-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
status:
  observedGeneration: 1
  lastScaleTime: <some-time>
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageUtilization: 0
          averageValue: 0
