apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-read-service
  namespace: bsk
  labels:
    app: rating-read-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating-read-service
  template:
    metadata:
      labels:
        app: rating-read-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "rating-read-service"
        dapr.io/app-port: "3000"
    spec:
      containers:
        - name: rating-read-service
          image: ghcr.io/tmogdans/bsk/rating-read-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: PORT
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: APP_NAME
            - name: NATS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: NATS_SERVER
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rating-read-service-db-url
                  key: url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
