apiVersion: v1
kind: Service
metadata:
  name: rating-write-service
  namespace: bsk
spec:
  type: NodePort
  selector:
    app: rating-write-service
  ports:
    - port: 80
      name: http
      targetPort: 3000
