packages:
  # Alle Services
  - "services/library-service"
  - "services/event-service"
  - "services/rating-write-service"
  - "services/rating-read-service"
  - "services/rating-view-service"
  # Gemeinsame Pakete
  - "packages/*"

catalog:
  # Core Dependencies
  "typescript": ^5.8.2
  "@types/node": ^22.13.9
  
  # Server
  "express": ^4.21.2
  "cors": ^2.8.5
  "helmet": ^7.1.0
  "morgan": ^1.10.0
  
  # Database
  "slonik": ^37.4.0
  "@slonik/migrator": ^0.18.1
  
  # Validation & Types
  "zod": ^3.22.4
  
  # Utilities
  "dotenv": ^16.4.5
  "pino": ^8.19.0
  "pino-pretty": ^10.3.1
  "slugify": ^1.6.6
  "date-fns": ^3.6.0
  
  # Messaging
  "nats": ^2.29.2
  
  # Build & Development Tools
  "vite": ^5.2.6
  "vite-plugin-node": ^5.0.0
  "vitest": ^1.5.1
  "@vitest/coverage-v8": ^1.5.1
  "@biomejs/biome": 1.7.0