packages:
  # Alle Services
  - "services/library-service"
  - "services/event-service"
  - "services/rating-write-service"
  - "services/rating-read-service"
  - "services/rating-view-service"
  # Gemeinsame Pakete
  - "packages/*"

catalog:
  "typescript": ^5.8.2
  "nats": ^2.29.2
  "@types/node": ^22.13.9
