apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: bsk
  labels:
    app: krakend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      enableServiceLinks: false
      containers:
        - name: krakend
          image: devopsfaith/krakend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          # Deaktivierung der Flexible Configuration, direktes Laden der Konfigurationsdatei
          env:
            - name: FC_ENABLE
              value: "0"
          volumeMounts:
            - name: krakend-config
              mountPath: /etc/krakend/krakend.json
              subPath: krakend.json
      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config
      restartPolicy: Always
