apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-read-service-db
  namespace: bsk
  labels:
    app: rating-read-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-read-service-db
  template:
    metadata:
      labels:
        app: rating-read-service-db
    spec:
      containers:
        - name: rating-read-service-db
          image: redis
          args: ["--appendonly", "yes"]
          ports:
            - containerPort: 6379
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
