apiVersion: v1
kind: Service
metadata:
  name: rating-read-service-db
  namespace: bsk
spec:
  type: NodePort
  selector:
    app: rating-read-service-db
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
