openapi: 3.0.1
info:
  title: event-service
  version: '1.0'
  license:
    name: MIT
servers:
  - url: 'http://localhost:8080'
    description: event-service
paths:
  /api/events:
    get:
      summary: get list of events
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
              examples:
                List of offline events:
                  value:
                    - id: 1
                      name: Mein erstes Event
                      slug: mein-erstes-event
                      type:
                        id: 1
                        name: convention
                        translated: Convention
                      beginsAt: '2022-09-01 10:00:00'
                      endsAt: '2022-09-01 20:00:00'
                      zip: '98765'
                      location: Musterhausen
                      country: de
                      street: Mustergasse 42b
                      description: lorem ipsum dolor
                      barrierFree: true
                      entryFree: true
                      onlineEvent: false
                      published: true
                      eventUrl: 'https://event.url'
                      createdAt: '2022-02-28 21:40:00'
                      updatedAt: '2022-02-28 21:40:00'
                      deletedAt: null
                      createdBy: 1
                      meta:
                        url: /events/mein-erstes-event
                List of online events:
                  value:
                    - id: 2
                      name: Mein online Event
                      slug: mein-online-event
                      type:
                        id: 1
                        name: convention
                        translated: Convention
                      beginsAt: '2022-09-01 10:00:00'
                      endsAt: '2022-09-01 20:00:00'
                      zip: null
                      location: null
                      country: de
                      street: null
                      description: lorem ipsum dolor
                      barrierFree: true
                      entryFree: true
                      onlineEvent: true
                      published: true
                      eventUrl: 'https://event.url'
                      createdAt: '2022-02-28 21:40:00'
                      updatedAt: '2022-02-28 21:40:00'
                      deletedAt: null
                      createdBy: 1
                      meta:
                        url: /events/mein-online-event
        '400':
          description: Bad Request
      operationId: get-events
      parameters:
        - schema:
            type: string
          in: header
          name: 'Accept: application/json'
          required: true
      description: Gibt eine Liste an Events zurück.
    parameters: []
    post:
      summary: add new event
      operationId: post-api-events
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
              examples:
                created offline event return:
                  value:
                    id: 1
                    name: Mein erstes Event
                    slug: mein-erstes-event
                    type:
                      id: 1
                      name: convention
                      translated: Convention
                    beginsAt: '2022-09-01 10:00:00'
                    endsAt: '2022-09-01 20:00:00'
                    zip: '98765'
                    location: Musterhausen
                    country: de
                    street: Mustergasse 42b
                    description: lorem ipsum dolor
                    barrierFree: true
                    entryFree: true
                    onlineEvent: false
                    published: true
                    eventUrl: 'https://event.url'
                    createdAt: '2022-02-28 21:40:00'
                    updatedAt: '2022-02-28 21:40:00'
                    deletedAt: null
                    createdBy: 1
                    meta:
                      url: /events/mein-erstes-event
        '400':
          description: Bad Request
      description: Neues Event hinzufügen
      parameters:
        - schema:
            type: string
          in: header
          name: 'Content-Type: application/json'
          required: true
        - schema:
            type: string
          in: header
          name: 'Accept: application/json'
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostEvent'
            examples:
              Create offline event:
                value:
                  name: Mein erstes Event
                  type: convention
                  beginsAt: '2022-09-01 10:00:00'
                  endsAt: '2022-09-01 20:00:00'
                  zip: '98765'
                  location: Musterhausen
                  country: de
                  street: Mustergasse 42b
                  description: lorem ipsum dolor
                  barrierFree: true
                  entryFree: true
                  onlineEvent: false
                  eventUrl: 'https://event.url'
        description: ''
  '/api/events/{slug}':
    parameters:
      - schema:
          type: string
        name: slug
        in: path
        required: true
    get:
      summary: get single event by slug
      tags: []
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    id: 1
                    name: Mein erstes Event
                    slug: mein-erstes-event
                    type:
                      id: 1
                      name: convention
                      translated: Convention
                    beginsAt: '2022-09-01 10:00:00'
                    endsAt: '2022-09-01 20:00:00'
                    zip: '98765'
                    location: Musterhausen
                    country: de
                    street: Mustergasse 42b
                    description: lorem ipsum dolor
                    barrierFree: true
                    entryFree: true
                    onlineEvent: false
                    published: true
                    eventUrl: 'https://event.url'
                    createdAt: '2022-02-28 21:40:00'
                    updatedAt: '2022-02-28 21:40:00'
                    deletedAt: null
                    createdBy: 1
                    meta:
                      url: /events/mein-erstes-event
                properties:
                  id:
                    type: number
                  name:
                    type: string
                    minLength: 1
                  slug:
                    type: string
                    minLength: 1
                  type:
                    $ref: '#/components/schemas/Type'
                  beginsAt:
                    type: string
                    minLength: 1
                  endsAt:
                    type: string
                    minLength: 1
                  zip:
                    type: string
                    minLength: 1
                  location:
                    type: string
                    minLength: 1
                  country:
                    type: string
                    minLength: 2
                    maxLength: 2
                  street:
                    type: string
                    minLength: 1
                  description:
                    type: string
                    minLength: 1
                  barrierFree:
                    type: boolean
                  entryFree:
                    type: boolean
                  onlineEvent:
                    type: boolean
                  published:
                    type: boolean
                  eventUrl:
                    type: string
                    minLength: 1
                  createdAt:
                    type: string
                    minLength: 1
                  updatedAt:
                    type: string
                    minLength: 1
                  deletedAt:
                    type: string
                    nullable: true
                  createdBy:
                    type: number
                  meta:
                    $ref: '#/components/schemas/Meta'
                required:
                  - id
                  - name
                  - slug
                  - type
                  - beginsAt
                  - endsAt
                  - zip
                  - location
                  - country
                  - street
                  - description
                  - barrierFree
                  - entryFree
                  - onlineEvent
                  - published
                  - eventUrl
                  - createdAt
                  - updatedAt
                  - createdBy
                  - meta
              examples:
                published offline barrierfree:
                  value:
                    id: 1
                    name: Mein erstes Event
                    slug: mein-erstes-event
                    type:
                      id: 1
                      name: convention
                      translated: Convention
                    beginsAt: '2022-09-01 10:00:00'
                    endsAt: '2022-09-01 20:00:00'
                    zip: '98765'
                    location: Musterhausen
                    country: de
                    street: Mustergasse 42b
                    description: lorem ipsum dolor
                    barrierFree: true
                    entryFree: true
                    onlineEvent: false
                    published: true
                    eventUrl: 'https://event.url'
                    createdAt: '2022-02-28 21:40:00'
                    updatedAt: '2022-02-28 21:40:00'
                    deletedAt: null
                    createdBy: 1
                    meta:
                      url: /events/mein-erstes-event
        '404':
          description: Not Found
      operationId: get single event
      description: Receive single event by its slug.
      parameters:
        - schema:
            type: string
          in: header
          name: Accept
          required: true
components:
  schemas:
    Event:
      title: Event
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        slug:
          type: string
        type:
          $ref: '#/components/schemas/Type'
        beginsAt:
          type: string
        endsAt:
          type: string
        zip:
          type: string
          nullable: true
        location:
          type: string
          nullable: true
        country:
          type: string
          minLength: 2
          maxLength: 2
        street:
          type: string
          nullable: true
        description:
          type: string
        barrierFree:
          type: boolean
        entryFree:
          type: boolean
        onlineEvent:
          type: boolean
        published:
          type: boolean
        eventUrl:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string
          nullable: true
        createdBy:
          type: integer
        meta:
          $ref: '#/components/schemas/Meta'
      required:
        - name
        - type
        - beginsAt
        - endsAt
        - country
        - description
    PostEvent:
      title: PostEventBody
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        beginsAt:
          type: string
        endsAt:
          type: string
        zip:
          type: string
          nullable: true
        location:
          type: string
          nullable: true
        country:
          type: string
          minLength: 2
          maxLength: 2
        street:
          type: string
          nullable: true
        description:
          type: string
        barrierFree:
          type: boolean
        entryFree:
          type: boolean
        onlineEvent:
          type: boolean
        eventUrl:
          type: string
      required:
        - name
        - type
        - beginsAt
        - endsAt
        - country
        - description
        - barrierFree
        - entryFree
        - onlineEvent
        - eventUrl
    Type:
      title: Type
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        translated:
          type: string
      required:
        - name
    Meta:
      title: Meta
      type: object
      properties:
        url:
          type: string
      description: Metainformationen
  parameters: {}
