apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: bsk
  labels:
    app: event-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: ghcr.io/tmogdans/bsk/event-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_NAME
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_ENV
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  key: password
                  name: event-service-app-key
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_DEBUG
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_URL
            - name: APP_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_TIMEZONE
            - name: APP_LOCALE
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_LOCALE
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: event-service-mysql-config-map
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-service-mysql-config-map
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: event-service-mysql-config-map
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: event-service-mysql-config-map
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: event-service-mysql-config-map
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: event-service-db-password
            - name: CACHE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: CACHE_DRIVER
            - name: QUEUE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: QUEUE_CONNECTION
      initContainers:
        - name: migrations
          image: ghcr.io/tmogdans/bsk/event-service:latest
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_NAME
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_ENV
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  key: password
                  name: event-service-app-key
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_DEBUG
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_URL
            - name: APP_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_TIMEZONE
            - name: APP_LOCALE
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: APP_LOCALE
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: event-service-mysql-config-map
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: event-service-mysql-config-map
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: event-service-mysql-config-map
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: event-service-mysql-config-map
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: event-service-mysql-config-map
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: event-service-db-password
            - name: CACHE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: CACHE_DRIVER
            - name: QUEUE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: event-service-environment-config-map
                  key: QUEUE_CONNECTION
      restartPolicy: Always
