apiVersion: v1
kind: ConfigMap
metadata:
  name: event-service-environment-config-map
  namespace: bsk
data:
  APP_NAME: "event-service"
  APP_ENV: "prod"
  APP_DEBUG: "false"
  APP_URL: "http://localhost"
  APP_TIMEZONE: "UTC"
  APP_LOCALE: "de"
  LOG_CHANNEL: "stdout"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
