apiVersion: v1
kind: ConfigMap
metadata:
  name: event-service-environment-config-map
  namespace: bsk
data:
  KEYCLOAK_BASE_URL: ""
  KEYCLOAK_REALM: "Brettspielkalender"
  KEYCLOAK_REALM_PUBLIC_KEY: ""
  KEYCLOAK_CLIENT_ID: "event-service"
