apiVersion: v1
kind: PersistentVolume
metadata:
  name: rating-write-service-postgres-pv-volume
  namespace: bsk
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rating-write-service-postgres-pv-claim
  namespace: bsk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
