apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: rating-read-service-db
  namespace: bsk
spec:
  version: 8.12.1
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
