apiVersion: v1
kind: Service
metadata:
  name: rating-read-service-db
  namespace: bsk
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: rating-read-service-db
  selector:
    app: rating-read-service-db
