natsBox:
  enabled: false

config:
  jetstream:
    enabled: true

    memoryStore:
      enabled: true
      maxSize: 256Mi

    memoryStore:
      enabled: true
      pvc:
        enabled: true
        size: 256Mi
