apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: bsk
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.10.0-alpine
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          ports:
            - containerPort: 4222
            - containerPort: 8222
