apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: bsk
spec:
  selector:
    app: nats
  ports:
    - name: "port-4222"
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: "port-8222"
      protocol: TCP
      port: 8222
      targetPort: 8222
