---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: library-service-db-password
  namespace: bsk
spec:
  encryptedData:
    password: AgBVbiruEKwgHAnrmuYSY589I6jAzh364XRwD7vTQbYVwWRheQ29egT+Y4rZzkkqZ5RJn59WVbgp/PXhLehVEBdaDOIev8S4rJ6lX6HBZGNfv+ean0WHPtWtSvBWeYCC32ESor2CgTzmxnHb0j4wIqZgLBbJgZF+s0t0Ze+vTojIj9klzDDEKnI+6Vfzd8O9vs3llOWbFjrIc68Nrr5Ar+iqWQgJ+QcROQ1tz1XlrioQbrFvWreqq4trQVqLHlZT7nYWca36QvzFX6/JywQo4atvHqDNoeRh1/trVeaZvp0DsNtvtRMRpXdfEKKM45CuBJO19zAwJo/fheuAIVG6BcoyRjHknwFGYZBL6QrPFNHNvITjQE+xTg2iB5bi4OVH/Mq0faqMWrsggfW0wVQUmAUIpEngif2XES+4AZkrh4eoR18Usq+QixqnaxV0aDzqwMzH7DGZPVl5JxCb5sxsSxhpYdOZzktMmI5isiJOc4HOrtIqUDCSf1oUdBoWwuerIFLhhJSSW1lG4aHzrXLsmAEbfebvnPaJ4P1O1+jGCZUQIonqv5jhGc3F2epS0UOBkX2x0eb2DUZB7U++m0NOLA0duHd5C9KZWDxUBHjhaWjYlsZVKM015i3nXILYym3lscf5v2qEnU6vnhljhXmrCVrvEoS+5PnPNhc6upZVWkxllAQiIL4hSPTaRl9ujE9fF6bxRWHLsXkq+kUvL25ew3QD2u+7vkTs8EXcNBK6ALSScQ==
  template:
    metadata:
      creationTimestamp: null
      name: library-service-db-password
      namespace: bsk
    type: Opaque
