apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: bsk
spec:
  type: ClusterIP
  selector:
    app: event-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000