---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: event-service-keycloak-client-secret
  namespace: bsk
spec:
  encryptedData:
    keycloak-client-secret: AgA+QggqTzvA3YGiHiMVBEtP295bHeOnnDL4akg0+YtMGJW1rjTqsRjaK8nHEy9OwbGUEDYFrEOpZbT45XsC72tmYszyJghJJmYJZOvAC/qyKDw2vzD/jNZ8lzlR/ha/WlnwAFEdTJfrYJr9dgnIHqnVqeSygxyEfaKnX3ulWWe2fIuKLHVV2+lPUROEjdFrq9/pkoHWZwPTrtsY/YGGFjSIKRoHmNELdiywqDBzCIR5JQHrMUiqdFTDK84EXVQ3kYLLsgFqj4OLj9qOTQNM9o/Al2JCvG2+tXjSxawj7+3NMS33TspWC0fVS7ZR2rcg3SZLVNURcnzF2lvWl4fR0zK+LY+rjvWN3Rn2IvjTc609GQRi05MDq/VkhEuHF85CqqeokfPf1hOaGf9XpsTjdZfhZc7QhHEIuYOw3e/b7i6Iqh1bj2/wi4qLYIc3QXb8gO95e6HiIBZmsZH8MkFHXg5opwMB2PMwpcQQTOVARlJd5Vpl5ZFv2sbpH2NRoLSCqTS7LmrdBgnWuTbFb9O2xTMEyR2fLPndnqtufXmH8F5St0KdOU4UzEBI+HHMYLna/8OzlTs1wDo3L+c1WubyTmvJmqArHlXjG1xgJjer6vzasU1LvTRSRShSBw+SIPXRBwoe7KoKya3dMvBt4LhAddL+utr0pwixItxG9m1E8V+sbqmnyGl9UrsoOyOgw4RsMbnLRwUdVJbrTfGcDw==
  template:
    metadata:
      creationTimestamp: null
      name: event-service-keycloak-client-secret
      namespace: bsk
    type: Opaque
