apiVersion: v1
kind: Service
metadata:
  name: rating-read-service
  namespace: bsk
spec:
  type: NodePort
  selector:
    app: rating-read-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
