apiVersion: v1
kind: Service
metadata:
  name: library-service
  namespace: bsk
spec:
  type: LoadBalancer
  selector:
    app: library-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
