apiVersion: v1
kind: Service
metadata:
  name: rating-write-service-db
  namespace: bsk
spec:
  type: NodePort
  selector:
    app: rating-write-service-db
  ports:
    - port: 5432
      targetPort: 5432
