apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rating-write-service
  namespace: bsk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rating-write-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 512
