apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-write-service
  namespace: bsk
  labels:
    app: rating-write-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-write-service
  template:
    metadata:
      labels:
        app: rating-write-service
    spec:
      containers:
        - name: rating-write-service
          image: ghcr.io/tmogdans/bsk/rating-write-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "600Mi"
            requests:
              memory: "512Mi"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: PORT
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: APP_NAME
            - name: NATS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: NATS_SERVER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-postgres-configmap
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rating-write-service-db-password
                  key: password
      restartPolicy: Always
