apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-write-service
  namespace: bsk
  labels:
    app: rating-write-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating-write-service
  template:
    metadata:
      labels:
        app: rating-write-service
    spec:
      containers:
        - name: rating-write-service
          image: ghcr.io/tmogdans/bsk/rating-write-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "600Mi"
            requests:
              memory: "512Mi"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: PORT
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: APP_NAME
            - name: NATS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: rating-write-service-environment-config-map
                  key: NATS_SERVER
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rating-write-service-db-url
                  key: url
      restartPolicy: Always
