apiVersion: v1
kind: Service
metadata:
  name: rating-write-service
  namespace: bsk
spec:
  type: LoadBalancer
  selector:
    app: rating-write-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
