name: rating-service CI

on:
  push:
    paths:
      - 'rating-service/api/**'
    branches:
      - rating-service
  pull_request:
    paths:
      - 'rating-service/api/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      working-directory: ./rating-service/api

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Test App
        run: npm run test
