name: rating-read-service CI

on:
  push:
    paths:
      - 'rating-read-service/api/**'
      - 'rating-read-service/deployment/**'
    branches:
      - main
  pull_request:
    paths:
      - 'rating-read-service/api/**'
      - 'rating-read-service/deployment/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build node service and test it
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      WORKING-DIRECTORY: ./rating-read-service/api

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci
        working-directory: ${{env.WORKING-DIRECTORY}}

      - name: Build App
        run: npm run build
        working-directory: ${{env.WORKING-DIRECTORY}}

      - name: Test App
        run: npm run test
        working-directory: ${{env.WORKING-DIRECTORY}}

  build_and_push:
    name: Build Docker image and push to ghcr
    needs: build_and_test
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: rating-read-service

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build rating-read-service Image
        uses: docker/build-push-action@v5
        with:
          context: ./rating-read-service
          file: ./rating-read-service/deployment/production/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/tmogdans/bsk/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
