name: rating-service CI

on:
  push:
    paths:
      - 'rating-service/api/**'
    branches:
      - rating-service
  pull_request:
    paths:
      - 'rating-service/api/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      WORKING-DIRECTORY: ./rating-service/api

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci
        working-directory: ${{env.WORKING-DIRECTORY}}

      - name: Build App
        run: npm run build
        working-directory: ${{env.WORKING-DIRECTORY}}

      - name: Test App
        run: npm run test
        working-directory: ${{env.WORKING-DIRECTORY}}

  build_and_push:
    name: Build Docker image and push to ghrc
    needs: build_and_test
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: rating-service
      WORKING-DIRECTORY: ./rating-service/deployment

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build rating-service Image
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          docker build . -f ./production/Dockerfile --tag ${{ env.REGISTRY }}/tmogdans/bsk/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/tmogdans/bsk/${{ env.IMAGE_NAME }}:latest
